spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      initial-size: 8
      max-active: 16
      min-idle: 8
      max-wait: 60000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    timeout: 60          #连接超时时间（毫秒）
    jedis:
      pool:
        max_total: 500   #控制一个pool可分配多少个jedis实例,用来替换max-active,如果是jedis 2.4以后用该属性
        #max-active: 10   #连接池最大连接数（负值表示没有限制）
        max-wait: 3000   #连接池最大阻塞等待时间（负值表示没有限制）
        max-idle: 10     #连接池最大空闲连接数
        min-idle: 1      #连接汉最小空闲连接数
        max_wait_millis: 1000 #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制
        min_evictable_idle_time_millis: 300000 #连接的最小空闲时间 默认1800000毫秒(30分钟)
        num_tests_per_eviction_run: 3    #每次释放连接的最大数目,默认3
        time_between_eviction_runs_millis: 30000  #逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程, 默认-1
        test_on_borrow: true  #是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
        test_while_idle: true #在空闲时检查有效性, 默认false
    key:
      apply_key: yyt_express_apply   # 应用缓存key


